### ISSUE TITLE
Test suite takes three hours to run on Julia nightly/master, but only 47 minutes to run on Julia 1.5.3

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaSIMD/LoopVectorization.jl#160]
On Julia 1.5.3, the test suite takes 47 minutes to run: https://github.com/chriselrod/LoopVectorization.jl/runs/1475169996

However, on Julia nightly/master, the test suite takes three hours to run: https://github.com/chriselrod/LoopVectorization.jl/runs/1475170020

GitHub Actions allows each job in a workflow to run for [up to 6 hours of execution time](https://docs.github.com/en/free-pro-team@latest/actions/reference/usage-limits-billing-and-administration). So we are under the limit there.

However, it is still concerning to see the duration of the test suite increase so drastically from Julia 1.5 to Julia nightly.

**Comment by chriselrod** [comment]
Yes, this is concerning.
Note that my test script is full of `@time`s. The outermost
``julia
10879.844959 seconds (2.22 G allocations: 124.094 GiB, 0.57% gc time, 99.54% compilation time)
```
This is just over 3 hours, 99.54% of which was compilation time.

Pumas also reported a compile time regression.

I suspect it has to do with heavily unrolled code. Pumas uses a lot of StaticArrays + ForwardDiff, while the benchmarks here that show a lot of slowdown are the heavily unrolled gemm kernels.

However, the convolutions in the offset array tests also feature pretty extreme unrolling if you have 32 registers (which the tests show), but it takes a fairly model 18 seconds. Earlier, these tests were taking many minutes on 1.6, so that's something to look into -- why isn't that happening anymore? Hopefully, there's a way to have the cake and eat it.

**Comment by chriselrod** [comment]
Seems to be function size more than unrolling.
`gemmaccurate` would be heavily unrolled, while `threegemms` shouldn't be worse than a normal gemm, but it should be a single function with three gemms inside it.
On Julia 1.5 (note, I'm copy and pasting in this way to make sure I'm recording all the compilation time):
```julia
julia> fill!(C, 9999.999);[

julia> t = time();

julia> gemm_accurate!(C, A, B);

julia> time() - t
2.180633068084717

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, At', B);

julia> time() - t
1.2518889904022217

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, A, Bt');

julia> time() - t
2.018035888671875

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, At', Bt');

julia> time() - t
2.27774715423584

julia> Ab = zeros(eltype(C), size(A)); Bb = zeros(eltype(C), size(B)); Cb = zero(C);

julia> t = time();

julia> threegemms!(Ab, Bb, Cb, A, B, C);

julia> time() - t
7.4180238246917725
```
On Julia master:
```julia
julia> t = time();

julia> gemm_accurate!(C, A, B);

julia> time() - t
5.641132116317749

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, At', B);

julia> time() - t
3.414412021636963

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, A, Bt');

julia> time() - t
5.563467979431152

julia> @test C ≈ C2
Test Passed

julia> fill!(C, 9999.999);

julia> t = time();

julia> gemm_accurate!(C, At', Bt');

julia> time() - t
7.038119077682495

julia> Ab = zeros(eltype(C), size(A)); Bb = zeros(eltype(C), size(B)); Cb = zero(C);

julia> t = time();

julia> threegemms!(Ab, Bb, Cb, A, B, C);

julia> time() - t
52.47762584686279
```

**Comment by DilumAluthge** [comment]
> This is just over 3 hours, 99.54% of which was compilation time.

I'm relieved to see that it was mostly compilation time. I was worried there were slowdowns in run time.

**Comment by DilumAluthge** [comment]
Here are the test suite times from `fded771`, which is the latest commit on LoopVectorization.jl `master`:

| Julia version | OS             | Arch | Time 1     | Time 2  |
| ------------- | -------------- | ---- | ---------- | ------- |
| 1.5.3         | Linux (Ubuntu) | x64  | 27m 27s    | 43m 26s |
| 1.5.3         | Windows        | x64  | 31m 29s    | 51m 3s  |
| nightly       | Linux (Ubuntu) | x64  | 2h 32m 25s |         |
| nightly       | Windows        | x64  | 28m 31s    |         |

**Comment by chriselrod** [comment]
Something to look at with the times is `LoopVectorization.REGISTER_COUNT = 16`, which prints as soon as the tests start.
```julia
   [4ec0a83e] Unicode
LoopVectorization.REGISTER_COUNT = 16
#= /home/runner/work/LoopVectorization.jl/LoopVectorization.jl/test/printmethods.jl:2 =# @__LINE__() = 2
```
This is a variable that influences how much unrolling LoopVectorization will do. The more named registers a CPU has, the more it is capable of unrolling without spilling registers to the stack. While it only does this when it thinks it will improve runtime, it does increase compile time, as more unrolling -> bigger functions to compile.

For nightly, the Windows time showed 16, and the Ubuntu time showed 32. That explains why Windows was so much faster.
Both "1.5" times showed 16, and both "1" (expanding to "1.5") times showed 32. Hence why we see such a big difference on the same Julia-version x OS combo: it's the REGISTER_COUNT variable that matters.

But then it is interesting to see that with REGISTER_COUNT = 16, Windows was faster on 1.6 than 1.5, although the difference is probably within noise.
But when `REGISTER_COUNT = 32`...

The problem seems to be the tests featuring extreme unrolling. I could disable them (e.g., `threegemms!`) when REGISTER_COUNT=32.
Is there an environmental variable that gets set when testing in Github Actions? If so, I could also use that to still run the tests locally. They're way faster than 3 hours on my personal computers.
FWIW, my personal computers have `32`, so I can identity the problematic functions locally.

**Comment by DilumAluthge** [comment]
> Is there an environmental variable that gets set when testing in Github Actions?

GitHub Actions will set the `GITHUB_ACTIONS` environment variable to `true`.

You could do:
```julia
function is_github_actions()
    return parse(Bool, get(ENV, "GITHUB_ACTIONS", "false"))
end
```

Is that what you had in mind?

**Comment by chriselrod** [comment]
Yes, thanks.

**Comment by DilumAluthge** [comment]
Out of curiosity, why is `REGISTER_COUNT` different on the Linux x64 machine versus the Windows x64 machine? As far as I am aware, the Linux and Windows jobs should be running on the same hardware

Hardware details here: https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners

Maybe it has something to do with the virtualization technologies that GitHub uses for the Linux vs Windows runners?

**Comment by chriselrod** [comment]
It seems to be random. Like why we got both 16 and 32 on 1.5 for both Windows and Linux.
If we rerun it, I think it could turn up the other way around.

Maybe I should add `InteractiveUtils` as a dependency so that I can start calling `versioninfo(verbose=true)` to get some more info.

Currently, 32 registers would mean Skylake-X, Cascadelake-X, or Cooperlake CPUs. Basically, recent Intel Xeons.
Older Xeons as well as AMD Epycs would have 16.
Specifying x86 yields 8.

**Comment by DilumAluthge** [comment]
Oh, I see what you mean. So it all depends on which machines Microsoft chooses for each job.

**Comment by chriselrod** [comment]
Yeah, and I imagine they have a lot of machines.

It was consistent on Travis. Macs had really old Xeons that didn't even have FMA or AVX2, while Linux always had AVX512.

**Comment by DilumAluthge** [comment]
> Maybe I should add `InteractiveUtils` as a dependency so that I can start calling `versioninfo(verbose=true)` to get some more info.

Implemented in: https://github.com/chriselrod/LoopVectorization.jl/pull/164

**Comment by DilumAluthge** [comment]
> Yeah, and I imagine they have a lot of machines.

Yeah and unfortunately, AFAICT, we can't specify what kind of chip they give us.

**Comment by DilumAluthge** [comment]
I looked at the three most recent commits on master, and the situation seems to be improved. No job seems to be taking more than 1.5 hours, which is pretty good I think. (E.g. this is the longest job I noticed out of all jobs in the three most recent commits on master: https://github.com/chriselrod/LoopVectorization.jl/runs/1536981516)

**Comment by chriselrod** [comment]
I fixed a bug/mistake in ArrayInterface that prevented OffsetArrays from being recognized as supported. Now:
https://github.com/chriselrod/LoopVectorization.jl/runs/1545836570?check_suite_focus=true
Maybe I should skip some of those tests.

**Comment by chriselrod** [comment]
Just got another failure
https://github.com/chriselrod/LoopVectorization.jl/actions/runs/426032789
```julia
   Expression: ELAPSED_MINUTES < 180
   Evaluated: 180.68036785125733 < 180
```

**Comment by DilumAluthge** [comment]
Hmmm that is concerning.

**Comment by DilumAluthge** [comment]
Do you think the chip is to blame? Looks like the failure ran on a Xeon.

**Comment by chriselrod** [comment]
Times aren't great, but better, especially on Julia 1.8 and newer.
