### ISSUE TITLE
error with erf 

### ISSUE THREAD

**Issue by CarloLucibello** [JuliaSIMD/LoopVectorization.jl#232]
Not sure this is the right place to ask (maybe VectorizationBase?) but this is what I get when I try to use `erf`

```julia
julia> using LoopVectorization, SpecialFunctions

julia> @avx for i=1:10
          a[i] = erf(x[i])
       end
ERROR: StackOverflowError:
Stacktrace:
 [1] erf(x::VectorizationBase.Vec{4, Float64}) (repeats 79984 times)
   @ SpecialFunctions ~/.julia/packages/SpecialFunctions/mFAQ4/src/erf.jl:10
```

Is `erf` support planned?

**Comment by chriselrod** [comment]
> Is `erf` support planned?

Yes. Not sure what the best way to do this is, because LoopVectorization & VectorizationBase don't depend on SpecialFunctions. Maybe use `Requires.jl`, which LoopVectorization is already using anyway.

The [current implementation](https://github.com/JuliaSIMD/VectorizationBase.jl/blob/6404e0dae5bc5c27859347e5ebdfda991cae414f/src/llvm_intrin/verf.jl) needs work, but:
```julia
julia> using LoopVectorization, SpecialFunctions, VectorizationBase

julia> x = randn(10); a = similar(x);

julia> @avx for i=1:10
           a[i] = VectorizationBase.verf(x[i])
       end

julia> a'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 0.565029  -0.59615  -0.382111  0.429077  -0.879287  -0.272737  0.43213  -0.937869  -0.917235  0.224102

julia> erf.(x)'
1×10 adjoint(::Vector{Float64}) with eltype Float64:
 0.565029  -0.59615  -0.382111  0.429077  -0.879287  -0.272737  0.43213  -0.937869  -0.917235  0.224102
```
The current implementation consists of copy/pastes of LLVM emitted by compiling the xsimd C++ library using Clang.
But it's not cross platform, because that IR uses target specific intrinsics, so while it should work on anything x64, it will not work on ARM.
While that could be solved by compiling ARM versions...
The better plan would be to just write Julia versions. Then they could also benefit from accepting `VecUnroll` arguments, which can give a fairly good % performance boost to special functions thanks to out of order execution.
