### ISSUE TITLE
Is it expected that splitting a loop with intermediate results may be faster than a single loop?

### ISSUE THREAD

**Issue by zsoerenm** [JuliaSIMD/LoopVectorization.jl#284]
Here are two versions of the same calculation:
```julia
using StructArrays, StaticArrays, BenchmarkTools, LoopVectorization
function downconvert_and_correlate(
    signal::StructArray{Complex{T}},
    code,
    shifts,
    carrier_frequency,
    sampling_frequency
) where {T}
    s_re = signal.re; s_im = signal.im
    a_re = zero(MVector{length(shifts), T})
    a_im = zero(MVector{length(shifts), T})
    @turbo for i = 1:2500
        c_im, c_re = sincos(T(2π) * ((i - 1) * T(carrier_frequency) / T(sampling_frequency)))
        ds_re = s_re[i] * c_re + s_im[i] * c_im
        ds_im = s_im[i] * c_re - s_re[i] * c_im
        for j = 1:length(a_re)
            sample_shift = shifts[j] - shifts[1]
            a_re[j] += ds_re * code[i + sample_shift]
            a_im[j] += ds_im * code[i + sample_shift]
        end
    end
    SVector(complex.(a_re, a_im))
end

function downconvert_and_correlate!(
    downconverted_signal::StructArray{Complex{T}},
    signal,
    code,
    shifts,
    carrier_frequency,
    sampling_frequency
) where {T}
    ds_re = downconverted_signal.re; ds_im = downconverted_signal.im
    s_re = signal.re; s_im = signal.im
    a_re = zero(MVector{length(shifts), T})
    a_im = zero(MVector{length(shifts), T})
    @turbo for i = 1:2500
        c_im, c_re = sincos(T(2π) * ((i - 1) * T(carrier_frequency) / T(sampling_frequency)))
        ds_re[i] = s_re[i] * c_re + s_im[i] * c_im
        ds_im[i] = s_im[i] * c_re - s_re[i] * c_im
    end
    @turbo for i = 1:2500
        for j = 1:length(a_re)
            sample_shift = shifts[j] - shifts[1]
            a_re[j] += ds_re[i] * code[i + sample_shift]
            a_im[j] += ds_im[i] * code[i + sample_shift]
        end
    end
    SVector(complex.(a_re, a_im))
end
```
The second function splits the loop into two loops and saves the results into an intermediate array.
Is it expected that splitting a loop with intermediate results may be faster than a single loop?
```julia
signal = StructArray(randn(ComplexF32, 2500))
code = Int8.(rand(Bool, 2502) * 2 .- 1)
shifts = SVector(-1,0,1)
@btime downconvert_and_correlate($signal, $code, $(SVector(-1, 0, 1)), $1500.0, $2.5e6)
# 4.354 μs (0 allocations: 0 bytes)

downconverted_signal = similar(signal)
@btime downconvert_and_correlate!($downconverted_signal, $signal, $code, $(SVector(-1, 0, 1)), $1500.0, $2.5e6)
#  3.034 μs (0 allocations: 0 bytes)
```

**Comment by chriselrod** [comment]
I tested on two different computers (Skylake-X and Haswell) and saw a much smaller difference than the nearly 50% difference you report here, but the split version was still faster.

I'm not sure about the cause, but I suspect `sincos` may be more efficient when it's on its own. Possible reasons:
1. Better out of order. It's unrolling the combined one by `(1,3)`, which corresponds to 3 calls of 1 vector. When `sincos` is on it's own, it'll unroll it by >=2, with a single call of multiple vectors. A single call of multiple vectors will interleave independent instructions, making out of order execution easier.
2. Hoisting constants. Evaluating `sincos` requires a lot of constants. x64 cores without AVX512 have only 16 floating point registers, which is not enough, meaning each loop iteration needs to reload many of these. The single call with multiple vectors would let a constant be reused for each vector, but that'll only work with the hoisted constants with multiple separate calls (i.e., those that can sit in registers in between loop iterations). The performance difference between the two versions was very small on my 7900X CPU (Skylake-X/has avx512, and hence 32 floating point registers): 2.1 vs 1.97 microseconds. This supports the idea that reloading constants was a factor.
3. Low level CPU stuff I don't know so much about. Skylake-X's loop stream detector (LSD) is disabled, for example, so that could contribute to the smaller difference. Maybe the simpler loops work better with it on other CPUs. But this and other low level details like this are things I don't know so much about.

**Comment by zsoerenm** [comment]
Thank you for the detailed answer! I think, I will leave it with two loops and close this for now.
