### ISSUE TITLE
Another reverse filling problem with 0.12.92

### ISSUE THREAD

**Issue by jaakkor2** [JuliaSIMD/LoopVectorization.jl#351]
A bit similar reverse filling loop as in #350 has problems with LoopVectorization 0.12.92
```
function foo2(n,m)
	A = zeros(n,2m)
	@turbo for i=1:n÷2, j = 1:m
		a = 1.23
		b = 3.21
		A[i, j] = a
		A[i, m+j] = b
		r = n + 1 - i
		A[r, j] = a
		A[r, m+j] = b
	end
	return A
end

foo2(5,3)
```
gives
```
5×6 Matrix{Float64}:
 1.23  1.23  1.23  3.21  3.21  3.21
 1.23  1.23  1.23  3.21  3.21  3.21
 0.0   3.21  3.21  3.21  0.0   0.0
 1.23  1.23  1.23  0.0   0.0   0.0
 1.23  1.23  1.23  0.0   0.0   0.0
```
and without `@turbo` the expected
```
5×6 Matrix{Float64}:
 1.23  1.23  1.23  3.21  3.21  3.21
 1.23  1.23  1.23  3.21  3.21  3.21
 0.0   0.0   0.0   0.0   0.0   0.0
 1.23  1.23  1.23  3.21  3.21  3.21
 1.23  1.23  1.23  3.21  3.21  3.21
```

**Comment by chriselrod** [comment]
Ha, thanks for the issues.

I changed some things with how indices are processed in 0.90, and apparently that wasn't well covered in the tests.

The problem in this case was that the (new) codepath followed by `A[r, m+j]` didn't increment a counter for many indices are processed, meaning it would first offset the first dimension by a constant `n+1`, and then offset the first (instead of the second) dimension by `m`.
